[workspace]
members = [
    "jitterentropy-bindgen",
    "jitterentropy-sys2",
    "rust-symcrypt",
    "symcrypt-bindgen",
    "symcrypt-sys"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.64.0"
