# adds missining dependencies into cross's container
# https://github.com/cross-rs/cross/wiki/FAQ#using-clang--bindgen
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
pre-build = [
    "echo 'running pre-build for aarch64-unknown-linux-gnu'",
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install --assume-yes clang libclang-dev",
    "apt-get install --assume-yes clang:arm64 libclang-dev:arm64",
    "file /usr/lib/llvm-10/lib/libclang-10.0.0.so"
]
