#include "symcrypt_internal_shared.inc"

#define _SYMCRYPT_STRING_INT(a) #a
#define _SYMCRYPT_STRING(a) _SYMCRYPT_STRING_INT(a)
<<<<<<< HEAD
#define SYMCRYPT_BUILD_INFO_BRANCH    "main"
#define SYMCRYPT_BUILD_INFO_COMMIT    "2025-01-27T19:44:15-05:00_53be637"
#define SYMCRYPT_BUILD_INFO_VERSION   _SYMCRYPT_STRING(SYMCRYPT_CODE_VERSION_API) "." _SYMCRYPT_STRING(SYMCRYPT_CODE_VERSION_MINOR) "." _SYMCRYPT_STRING(SYMCRYPT_CODE_VERSION_PATCH)
#define SYMCRYPT_BUILD_INFO_TIMESTAMP "2025-02-05T15:08:23"
=======
#define SYMCRYPT_BUILD_INFO_BRANCH    ""
#define SYMCRYPT_BUILD_INFO_COMMIT    "2025-01-28T01:44:15+01:00_53be637"
#define SYMCRYPT_BUILD_INFO_VERSION   _SYMCRYPT_STRING(SYMCRYPT_CODE_VERSION_API) "." _SYMCRYPT_STRING(SYMCRYPT_CODE_VERSION_MINOR) "." _SYMCRYPT_STRING(SYMCRYPT_CODE_VERSION_PATCH)
#define SYMCRYPT_BUILD_INFO_TIMESTAMP "2025-01-31T15:53:40"
>>>>>>> main
