#include "symcrypt_internal_shared.inc"

#define _SYMCRYPT_JOIN(a, b) #a "." #b
#define _SYMCRYPT_EXPAND_JOIN(a, b) _SYMCRYPT_JOIN(a, b)
#define SYMCRYPT_BUILD_INFO_BRANCH    ""
#define SYMCRYPT_BUILD_INFO_COMMIT    "2024-04-12T07:54:16+02:00_171f697"
#define SYMCRYPT_BUILD_INFO_VERSION   _SYMCRYPT_EXPAND_JOIN(_SYMCRYPT_EXPAND_JOIN(SYMCRYPT_CODE_VERSION_API, SYMCRYPT_CODE_VERSION_MINOR), SYMCRYPT_CODE_VERSION_PATCH)
#define SYMCRYPT_BUILD_INFO_TIMESTAMP "2025-01-14T14:29:07"
