[package]
name = "symcrypt-sys"
authors = ["Microsoft"]
version = "0.5.0"
license = "MIT OR Apache-2.0"
description = "Rust/C Bindings for SymCrypt"
edition.workspace = true
rust-version.workspace = true
build = "build.rs"
homepage = "https://github.com/microsoft/SymCrypt"
repository = "https://github.com/microsoft/rust-symcrypt"
readme = "README.md"
links = "symcrypt"
categories = ["cryptography", "external-ffi-bindings"]
keywords = ["symcrypt", "crypto", "ffi", "fips", "bindings"]

[dependencies]
libc = { workspace = true }
