/* automatically generated by rust-bindgen 0.71.1 */

use super::types::*;

pub const SYMCRYPT_CODE_VERSION_API: u32 = 103;
pub const SYMCRYPT_CODE_VERSION_MINOR: u32 = 4;
pub const SYMCRYPT_CODE_VERSION_PATCH: u32 = 2;
pub const SYMCRYPT_MD5_RESULT_SIZE: u32 = 16;
pub const SYMCRYPT_SHA1_RESULT_SIZE: u32 = 20;
pub const SYMCRYPT_SHA256_RESULT_SIZE: u32 = 32;
pub const SYMCRYPT_SHA384_RESULT_SIZE: u32 = 48;
pub const SYMCRYPT_SHA512_RESULT_SIZE: u32 = 64;
pub const SYMCRYPT_SHA3_256_RESULT_SIZE: u32 = 32;
pub const SYMCRYPT_SHA3_384_RESULT_SIZE: u32 = 48;
pub const SYMCRYPT_SHA3_512_RESULT_SIZE: u32 = 64;
pub const SYMCRYPT_AES_BLOCK_SIZE: u32 = 16;
pub const SYMCRYPT_FLAG_ECKEY_ECDSA: u32 = 4096;
pub const SYMCRYPT_FLAG_ECKEY_ECDH: u32 = 8192;
pub const SYMCRYPT_FLAG_RSAKEY_SIGN: u32 = 4096;
pub const SYMCRYPT_FLAG_RSAKEY_ENCRYPT: u32 = 8192;
pub const SYMCRYPT_FLAG_RSA_PKCS1_NO_ASN1: u32 = 1;
pub const SYMCRYPT_FLAG_RSA_PKCS1_OPTIONAL_HASH_OID: u32 = 2;
unsafe extern "C" {
    pub static SymCryptMd5Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha1Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha256Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha384Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha512Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha3_256Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha3_384Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptSha3_512Algorithm: PCSYMCRYPT_HASH;
}
unsafe extern "C" {
    pub static SymCryptHmacMd5Algorithm: PCSYMCRYPT_MAC;
}
unsafe extern "C" {
    pub static SymCryptHmacSha1Algorithm: PCSYMCRYPT_MAC;
}
unsafe extern "C" {
    pub static SymCryptHmacSha256Algorithm: PCSYMCRYPT_MAC;
}
unsafe extern "C" {
    pub static SymCryptHmacSha384Algorithm: PCSYMCRYPT_MAC;
}
unsafe extern "C" {
    pub static SymCryptHmacSha512Algorithm: PCSYMCRYPT_MAC;
}
unsafe extern "C" {
    pub static SymCryptAesBlockCipher: PCSYMCRYPT_BLOCKCIPHER;
}
unsafe extern "C" {
    pub static SymCryptEcurveParamsNistP256: PCSYMCRYPT_ECURVE_PARAMS;
}
unsafe extern "C" {
    pub static SymCryptEcurveParamsNistP384: PCSYMCRYPT_ECURVE_PARAMS;
}
unsafe extern "C" {
    pub static SymCryptEcurveParamsNistP521: PCSYMCRYPT_ECURVE_PARAMS;
}
unsafe extern "C" {
    pub static SymCryptEcurveParamsCurve25519: PCSYMCRYPT_ECURVE_PARAMS;
}
unsafe extern "C" {
    pub static SymCryptMd5OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha1OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha256OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha384OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha512OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha3_256OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha3_384OidList: [SYMCRYPT_OID; 2usize];
}
unsafe extern "C" {
    pub static SymCryptSha3_512OidList: [SYMCRYPT_OID; 2usize];
}
