[package]
name = "symcrypt"
authors = ["Microsoft"]
version = "0.6.0"
license = "MIT OR Apache-2.0"
description = "Friendly and Idiomatic Wrappers for SymCrypt"
edition.workspace = true
rust-version.workspace = true
homepage = "https://github.com/microsoft/SymCrypt"
repository = "https://github.com/microsoft/rust-symcrypt"
readme = "README.md"
categories = ["cryptography", "api-bindings"]
keywords = ["symcrypt", "crypto", "fips", "encryption", "hashing"]

[dependencies]
symcrypt-sys = { workspace = true }
libc = { workspace = true }

[features]
default = []
md5 = []
sha1 = []
pkcs1-encrypt-decrypt = []

[dev-dependencies]
hex = { workspace = true }
