name: Bindgen

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  bindgen:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc, x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          command: cargo
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          command: cargo
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-24.04
          command: cargo
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-24.04
          command: cross

    runs-on: ${{ matrix.os }}
    name: Bindgen ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install host target
      shell: pwsh
      run: rustup target add ${{ matrix.target }}

    - name: Install cross
      if: ${{ matrix.command }} == 'cross'
      uses: taiki-e/install-action@v2
      with:
        tool: cross


    - name: Compare generated bindings
      shell: pwsh
      run: |
        ${{ matrix.command }} run --locked --bin symcrypt-bindgen ${{ matrix.target }} ${{ runner.temp }}
        $targetName = "${{ matrix.target }}".Replace("-", "_")
        $newBindingsFile = "${{ runner.temp }}/$targetName.rs"
        $oldBindingsFile = "./symcrypt-sys/src/bindings/$targetName.rs"
        $diff = git diff --no-index $newBindingsFile $oldBindingsFile
        if ($diff) {
          Write-Output "Bindings have changed"
          Write-Output $diff
          exit 1
        } else {
          Write-Output "Bindings are up to date"
        }
