name: Bindgen

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  NEW_BINDINGS_TARGET_FOLDER: "./target/__bindgen"

jobs:
  bindgen:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc, x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          command: cargo
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          command: cargo
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-24.04
          command: cargo
        # cross fails with error below:
        # Unable to find libclang: "the `libclang` shared library at /usr/lib/llvm-10/lib/libclang-10.0.0.so
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-24.04
          command: cargo

    runs-on: ${{ matrix.os }}
    name: Bindgen ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install host target
      if: ${{ matrix.command != 'cross' }}
      shell: pwsh
      run: |
        rustup target add ${{ matrix.target }}
        if ("${{ matrix.target }}" -match "aarch64-unknown-linux-gnu") {
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        }

    - name: Install cross
      if: ${{ matrix.command == 'cross' }}
      uses: taiki-e/install-action@v2
      with:
        tool: cross

    - name: Build
      run:  ${{ matrix.command }} build -p symcrypt-bindgen --locked --verbose --target ${{ matrix.target }}

    - name: Generate bindings (cross)
      if: ${{ matrix.command == 'cross' }}
      run: ${{ matrix.command }} run --locked --bin symcrypt-bindgen --target ${{ matrix.target }} -- ${{ matrix.target }} ${{ env.NEW_BINDINGS_TARGET_FOLDER }}

    - name: Generate bindings (cargo)
      if: ${{ matrix.command != 'cross' }}
      run: ${{ matrix.command }} run --locked --bin symcrypt-bindgen -- ${{ matrix.target }} ${{ env.NEW_BINDINGS_TARGET_FOLDER }}

    - name: Compare generated bindings
      shell: pwsh
      run: |
        $targetName = "${{ matrix.target }}".Replace("-", "_")

        $newBindingsFile = "${{ env.NEW_BINDINGS_TARGET_FOLDER }}/$targetName.rs"
        $oldBindingsFile = "./symcrypt-sys/src/bindings/$targetName.rs"
        $diff = git diff --no-index $newBindingsFile $oldBindingsFile
        if ($diff) {
          Write-Output "Bindings have changed"
          Write-Output $diff
          exit 1
        } else {
          Write-Output "Bindings are up to date"
        }
