name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  FEATURES_TO_TEST: md5,sha1,pkcs1-encrypt-decrypt

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.8.0/symcrypt-windows-amd64-release-103.8.0-53be637d.zip"
          run-tests: true
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.8.0/symcrypt-windows-arm64-release-103.8.0-53be637d.zip"
          run-tests: false # Windows doesn't support ARM64 emulation
        - target: x86_64-unknown-linux-gnu
          symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.8.0/symcrypt-linux-generic-amd64-release-103.8.0-53be637.tar.gz"
          os: ubuntu-latest
          run-tests: true
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-latest
          symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.8.0/symcrypt-linux-generic-arm64-release-103.8.0-53be637.tar.gz"
          run-tests: false
            
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}    
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install host target
      shell: pwsh
      run: |
        rustup target add ${{ matrix.target }}
        if ("${{ matrix.target }}" -match "aarch64-unknown-linux-gnu") {
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        }

    - uses: Swatinem/rust-cache@v2

    - name: Download SymCrypt
      shell: pwsh
      run: |
        $dir = $(Get-Item .).FullName
        if ("${{ matrix.symcrypt }}" -match "\.tar\.gz$") {
          Invoke-WebRequest -Uri ${{ matrix.symcrypt }} -OutFile symcrypt.tar.gz
          New-Item -ItemType Directory -Force -Path symcrypt
          tar -xzf symcrypt.tar.gz -C symcrypt
          echo "$dir/symcrypt/lib" >> $env:GITHUB_PATH
          echo "LD_LIBRARY_PATH=$dir/symcrypt/lib:$env:LD_LIBRARY_PATH" >> $env:GITHUB_ENV
          echo "LIBRARY_PATH=$dir/symcrypt/lib:$env:LIBRARY_PATH" >> $env:GITHUB_ENV
          echo "SYMCRYPT_LIB_PATH=$dir/symcrypt/lib" >> $env:GITHUB_ENV
        } else {
          Invoke-WebRequest -Uri ${{ matrix.symcrypt }} -OutFile symcrypt.zip
          New-Item -ItemType Directory -Force -Path symcrypt
          Expand-Archive -Path symcrypt.zip -DestinationPath symcrypt
          echo "$dir/symcrypt/dll" >> $env:GITHUB_PATH
          echo "SYMCRYPT_LIB_PATH=$dir/symcrypt/dll" >> $env:GITHUB_ENV   
        }

    - name: Debug build
      run: cargo build --locked --verbose --target ${{ matrix.target }}
    
    - name: Release build
      run: cargo build --release --locked --verbose --target ${{ matrix.target }}

    - name: Run tests (Debug, dynamic)
      if: matrix.run-tests
      run: cargo test --locked --verbose --all-features --target ${{ matrix.target }}

    - name: Run tests (Release, dynamic)
      if: matrix.run-tests
      run: cargo test --release --locked --verbose --all-features --target ${{ matrix.target }}

    - name: Run test (Debug, static)
      if: matrix.run-tests
      run: cargo test --features ${{ env.FEATURES_TO_TEST }} --locked --target ${{ matrix.target }}

    - name: Run test (Release, static)
      if: matrix.run-tests
      run: cargo test --features ${{ env.FEATURES_TO_TEST }} --locked --target ${{ matrix.target }}
