name: Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  FEATURES_TO_TEST: md5,sha1,pkcs1-encrypt-decrypt

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          runs-on: ubuntu-latest
          run-tests: true
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-24.04-arm
          runs-on: ubuntu-24.04-arm
          run-tests: true
          
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}    
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        submodules: true

    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

    # Download SymCrypt via PMC
    - name: Install SymCrypt via PMC
      shell: bash
      run: |
        curl -sSL -O https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y symcrypt
    
    - name: Install host target
      shell: pwsh
      run: |
        rustup target add ${{ matrix.target }}
        if ("${{ matrix.target }}" -match "aarch64-unknown-linux-gnu") {
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        }

    - name: Debug build
      run: cargo build --locked --verbose --target ${{ matrix.target }}
    
    - name: Release build
      run: cargo build --release --locked --verbose --target ${{ matrix.target }}

    - name: Run tests (Debug)
      if: matrix.run-tests
      run: cargo test --locked --verbose --all-features --target ${{ matrix.target }}

    - name: Run tests (Release)
      if: matrix.run-tests
      run: cargo test --release --locked --verbose --all-features --target ${{ matrix.target }}
