name: Cargo Clippy Check

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  SYMCRYPT_LIB_PATH: "/dev/null" # Dummy value to bypass the env variable check on Windows


jobs:
  clippy:
    name: Clippy Check
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm] # Run on x86_64 and arm64 for Linux and Windows

    steps:
      - name: Checkout sources
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          submodules: true

      - name: Install Rust toolchain 
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
